languange: ruby

rvm:
  - 2.5.1

services:
  - docker

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -t brianmmcclain/ruby-travis-demo:$TRAVIS_BUILD_NUMBER .
  - docker push brianmmcclain/ruby-travis-demo:$TRAVIS_BUILD_NUMBER